# Generated by Django 5.1.1 on 2024-10-20 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_address', models.TextField()),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('package_details', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_type', models.CharField(choices=[('Fragile', 'Fragile'), ('Standard', 'Standard')], max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('pickup_date', models.DateField()),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='item_photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.register')),
            ],
        ),
    ]
