# Generated by Django 5.1.1 on 2024-10-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courierbooking',
            old_name='receiver_address',
            new_name='destination_address',
        ),
        migrations.RenameField(
            model_name='courierbooking',
            old_name='sender_address',
            new_name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='courierbooking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='courierbooking',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='courierbooking',
            name='destination_city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kochi', 'Kochi'), ('Kozhikode', 'Kozhikode')], default='kochi', max_length=100),
        ),
        migrations.AddField(
            model_name='courierbooking',
            name='destination_pincode',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='courierbooking',
            name='pickup_city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kochi', 'Kochi'), ('Kozhikode', 'Kozhikode')], default='kochi', max_length=100),
        ),
        migrations.AddField(
            model_name='courierbooking',
            name='receiver_phone',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='courierbooking',
            name='tracking_id',
            field=models.CharField(default=0, editable=False, max_length=6, unique=True),
        ),
    ]
