# Generated by Django 5.1.1 on 2024-10-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_receiver_address_courierbooking_destination_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierbooking',
            name='destination_pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='courierbooking',
            name='receiver_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='courierbooking',
            name='tracking_id',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
