# Generated by Django 5.1.1 on 2024-10-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_courierbooking_destination_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierbooking',
            name='destination_city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kochi', 'Kochi'), ('Kozhikode', 'Kozhikode')], max_length=100),
        ),
        migrations.AlterField(
            model_name='courierbooking',
            name='pickup_city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kochi', 'Kochi'), ('Kozhikode', 'Kozhikode')], max_length=100),
        ),
    ]
