# Generated by Django 5.1.1 on 2024-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_courierbooking_destination_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierbooking',
            name='package_details',
        ),
        migrations.AddField(
            model_name='courierbooking',
            name='receiver_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
