# Generated by Django 5.1.1 on 2024-11-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_courierbooking_package_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierbooking',
            name='picked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courierbooking',
            name='picked_status',
            field=models.BooleanField(default=False),
        ),
    ]
