# Generated by Django 5.1.1 on 2024-11-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_courierbooking_picked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierbooking',
            name='destination_city',
            field=models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Kannur', 'Kannur'), ('Wayanad', 'Wayanad'), ('Kasargod', 'Kasargod'), ('Thrissur', 'Thrissur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='courierbooking',
            name='pickup_city',
            field=models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Kannur', 'Kannur'), ('Wayanad', 'Wayanad'), ('Kasargod', 'Kasargod'), ('Thrissur', 'Thrissur')], max_length=100),
        ),
    ]
