# Generated by Django 5.1.1 on 2024-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_courierbooking_destination_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierbooking',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courierbooking',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courierbooking',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Picked Up', 'Picked Up'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
