# Generated by Django 5.1.1 on 2024-11-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_courierbooking_delivered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierbooking',
            name='item_type',
            field=models.CharField(choices=[('Fresh Items', 'Fresh Items'), ('Breakables', 'Breakables'), ('Health Supplies', 'Health Supplies'), ('Everyday Goods', 'Everyday Goods')], max_length=50),
        ),
    ]
